server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://xxx:3306/xxxx?useSSL=false&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: xxx
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 30
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      validation-query: SELECT 'x'
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      filters: stat,wall
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      indent_output: true
  output:
    ansi:
      enabled: detect
  aop:
    proxy-target-class: true
  session:
    store-type: redis
    hazelcast:
      flush-mode: on_save
    redis:
      namespace: spring:session
logging:
  config: classpath:log/logback-spring.xml
  level:
    com:
      gpu:
        epidemic: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gpu.epidemic.*.entity,com.gpu.epidemic.*.mapper
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true


