server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://xxx:3306/xxxx?useSSL=false&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: xxx
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 30
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      validation-query: SELECT 'x'
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      filters: stat,wall
logging:
  level:
    com.gpu.epidemic: debug
  file:
    total-size-cap: 2GB
    name: ${logging.file.path}/epidemic.log
    path: logs
    max-size: 10MB
    max-history: 30
  pattern:
    rolling-file-name: ${logging.file.path}/oauth-service.%d{yyyy-MM-dd}-%i.log
mybatis-plus:
  configuration:
    cache-enabled: false


